import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Application Operating System — Angel Vergara", description: "A controlled workflow for matching verified roles to truthful, tailored application packages." };

const steps = [["01", "Verify role", "Official posting, location, compensation, current status"], ["02", "Choose lane", "Implementation, business systems, or AI workflow"], ["03", "Match proof", "Shipped product plus the most relevant case study"], ["04", "Tailor package", "Summary, keywords, letter, and factual claims"], ["05", "Submit & log", "Date, source, material version, and next action"], ["06", "Follow up", "Recruiter touch, outcome, and learning loop"]];

export default function ApplicationKitPage() {
  return <main id="main">
    <section className="app-hero"><div className="shell app-hero-grid"><div><p className="eyebrow light-eyebrow">Career application operating system</p><h1>Fastest credible conversion first. Higher-pay bridges next.</h1><p className="lede">A practical system for moving from a verified opportunity to a truthful, tailored application without losing proof, context, or follow-up.</p><div className="actions"><a className="button light-button" href="/downloads/Angel_Vergara_Application_Quickstart.pdf" download>Download quickstart <span>↓</span></a><Link className="button outline-light" href="/resume">Choose a resume <span>→</span></Link></div></div><div className="app-hero-note"><span>Positioning order</span><b>Implementation first</b><b>Business systems bridge</b><b>Selective AI upside</b><small>Every role is reverified immediately before submission.</small></div></div></section>
    <section className="flow-section"><div className="shell"><div className="split-head"><div><p className="eyebrow">Controlled workflow</p><h2>Every application moves through the same six gates.</h2></div><p>The system keeps speed and truth aligned: the role is live, the resume lane is deliberate, the proof is relevant, and follow-up is assigned.</p></div><div className="application-flow">{steps.map(([n, title, copy]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="dashboard-proof"><div className="shell"><div className="split-head"><div><p className="eyebrow">Visual command center</p><h2>A dashboard that makes the next move obvious.</h2></div><p>This portfolio snapshot shows the operating design, not a live opportunity list. Official postings and compensation are rechecked before every application.</p></div><figure className="dashboard-frame"><img src="/images/portfolio/application-dashboard.png" alt="Application dashboard with role prioritization, resume lanes, and application workflow" /><figcaption><span>Private working dashboard preview</span><span>Snapshot · July 18, 2026</span></figcaption></figure></div></section>
    <section className="package-section dark-section"><div className="shell"><div className="split-head"><div><p className="eyebrow">Role package anatomy</p><h2>One submission package. Seven aligned surfaces.</h2></div><p>A role pack is useful only when the resume, cover note, portfolio evidence, and recruiter message tell the same factual story.</p></div><div className="package-grid">{[["01", "Official role brief"], ["02", "Fit and gap analysis"], ["03", "Selected resume lane"], ["04", "Tailored cover note"], ["05", "Portfolio proof order"], ["06", "Recruiter message"], ["07", "Submission + follow-up log"]].map(([n, item]) => <article key={n}><span>{n}</span><b>{item}</b></article>)}</div></div></section>
    <section className="strategy-section"><div className="shell"><div className="split-head"><div><p className="eyebrow">Market strategy</p><h2>Optimize for conversion and compensation—without pretending gaps do not exist.</h2></div><p>The fastest path is where Angel’s domain credibility, bilingual communication, implementation judgment, and public product proof are all visible on the first screen.</p></div><div className="strategy-grid"><article className="featured-strategy"><span>Primary · Fastest credible conversion</span><h3>Implementation & onboarding</h3><ul><li>Bilingual hospitality technology onboarding</li><li>SaaS implementation and configuration</li><li>Customer training, adoption, and enablement</li><li>Operations-software implementation</li></ul></article><article><span>Bridge · Higher pay</span><h3>Business systems</h3><ul><li>Operations and workforce analysis</li><li>Business systems implementation</li><li>Process and requirements analysis</li></ul></article><article><span>Selective · High upside</span><h3>AI workflows</h3><ul><li>AI process and implementation roles</li><li>Workflow automation consulting</li><li>Integration roles that value domain fluency</li></ul></article></div></div></section>
    <section className="materials-cta"><div className="shell application-grid"><div><p className="eyebrow light-eyebrow">Ready-to-use materials</p><h2>Open the right artifact and move.</h2><p>The internal Notion workspace remains the source of truth for live role packs and submission tracking. Public downloads contain the polished, employer-facing materials.</p></div><div className="application-links"><a href="/downloads/Angel_Vergara_Cover_Letter_Kit.pdf" download><span>Cover-letter kit</span><span>↓</span></a><a href="/downloads/Angel_Vergara_Application_Quickstart.pdf" download><span>Application quickstart</span><span>↓</span></a><a href="https://app.notion.com/p/390f99e853ab81e2bcd8e17d5c9ae743" target="_blank" rel="noreferrer"><span>Private Notion dashboard</span><span>↗</span></a></div></div></section>
  </main>;
}
