import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Resumes & Career Materials — Angel Vergara", description: "Three ATS-readable resume lanes for implementation, business systems, and AI workflow roles." };

const lanes = [
  { number: "01", title: "Implementation & Onboarding", fit: "Best first choice", tone: "cobalt", file: "Angel_Vergara_Resume_Implementation_Onboarding.pdf", roles: ["Hospitality technology onboarding", "SaaS implementation specialist", "Customer training & adoption", "Technical customer success"], proof: "Leads with bilingual operations leadership, training, configuration, workflow discovery, and customer-ready implementation." },
  { number: "02", title: "Business Systems & Operations", fit: "High-pay bridge", tone: "ink", file: "Angel_Vergara_Resume_Business_Systems_Operations.pdf", roles: ["Business systems analyst", "Operations analyst", "Workforce optimization", "Implementation consultant"], proof: "Leads with process discovery, requirements, operating controls, reporting, vendors, inventory, payroll coordination, and systems thinking." },
  { number: "03", title: "AI Workflow & Automation", fit: "Selective upside", tone: "copper", file: "Angel_Vergara_Resume_AI_Workflow_Automation.pdf", roles: ["AI process analyst", "Workflow automation analyst", "AI implementation specialist", "Solutions / integration consultant"], proof: "Leads with shipped public product work, governed agentic workflows, LLM integration, human approval gates, and evidence-backed delivery." },
];

export default function ResumePage() {
  return <main id="main">
    <section className="subpage-hero"><div className="shell"><p className="eyebrow">Resume suite · Verified career evidence</p><h1>One career.<br />Three employer-ready views.</h1><p className="lede">Choose the lane that matches the employer’s first screen. The positioning changes; the experience, dates, education, and factual proof stay consistent.</p></div></section>
    <section className="resume-lane-section"><div className="shell lane-stack">{lanes.map((lane) => <article className={`lane-card ${lane.tone}`} key={lane.number}><div className="lane-number">{lane.number}</div><div><span className="status-dot">{lane.fit}</span><h2>{lane.title}</h2><p>{lane.proof}</p><ul>{lane.roles.map((role) => <li key={role}>{role}</li>)}</ul></div><div className="lane-download"><div className="resume-paper large-paper" aria-hidden="true"><b>Angel Vergara</b><span>{lane.title}</span><i></i><i></i><i></i><i></i><i></i><i></i></div><a className="button primary" href={`/downloads/${lane.file}`} download>Download PDF <span aria-hidden="true">↓</span></a></div></article>)}</div></section>
    <section className="truth-section dark-section"><div className="shell split-head"><div><p className="eyebrow">The shared evidence spine</p><h2>Truth stays fixed across every lane.</h2></div><div className="truth-grid"><div><b>15+ years</b><span>Hospitality and food-and-beverage operations</span></div><div><b>English / Español</b><span>Bilingual communication and training</span></div><div><b>Shipped product</b><span>Resale Scanner Pro live and publicly inspectable</span></div><div><b>Education</b><span>FIU · CIA · Valencia</span></div></div></div></section>
    <section className="materials-section"><div className="shell"><div className="split-head"><div><p className="eyebrow">Application materials</p><h2>Start with proof. Tailor only what changes the decision.</h2></div><p>The cover-letter and quickstart kits make the application process repeatable without turning every submission into a rewrite.</p></div><div className="material-grid"><article><span className="card-tag">Writing system</span><h3>Cover-letter kit</h3><p>A relevant opening, operating credibility, one portfolio proof, and a low-friction close—with lane-specific guidance for implementation, systems, and AI roles.</p><a className="button" href="/downloads/Angel_Vergara_Cover_Letter_Kit.pdf" download>Download kit <span aria-hidden="true">↓</span></a></article><article><span className="card-tag">Application workflow</span><h3>Application quickstart</h3><p>A concise guide for verifying the role, choosing the resume lane, matching proof, tailoring claims, submitting, and following up.</p><a className="button" href="/downloads/Angel_Vergara_Application_Quickstart.pdf" download>Download quickstart <span aria-hidden="true">↓</span></a></article><article className="blue-material"><span className="card-tag">System view</span><h3>Application operating system</h3><p>See how the dashboard, role packs, recruiter messaging, and tracking workflow fit together.</p><Link className="button light-button" href="/application-kit">Open the application kit <span aria-hidden="true">→</span></Link></article></div></div></section>
  </main>;
}
